It's 2024 now
AerospaceNU/stm32-avionics pull request #289
Opened 2024-01-18 01:47 UTC by trholdridge

I want commit history

2024-01-18 02:07 UTC, irisnwang commented
hey bby ;) i liked your PR... and thats not the only thing i like ;)

2024-01-18 02:45 UTC, mcm001 requested changes
No

2024-01-18 02:46 UTC, mcm001 approved these changes

2024-01-19 04:59 UTC, SamHaggans approved these changes

2024-01-19 05:17 UTC, merged